version: '3.7'
services:
  mongo:
    container_name: ags-mongo
    image: mongo:4.2.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - type: bind
        source: ./volume/mongo
        target: /data/db
    ports:
      - "27017:27017"

  redis:
    container_name: ags-redis
    image: redis:5.0.8
    ports:
      - "6379:6379"
